import "./globals.css";

import type { Metadata } from "next";
import { Inter, Bricolage_Grotesque } from "next/font/google";

import { cn } from "@/lib/utils";
import ReactQueryProviders from "@/components/provider/tanstack-query-provider";
import AuthDialog from "@/components/auth-dialog";

const fontSans = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const fontHeading = Bricolage_Grotesque({
  variable: "--font-heading",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen font-sans antialiased",
          fontSans.variable,
          fontHeading.variable,
        )}
      >
        <ReactQueryProviders>
          <main>
            {children}
            <AuthDialog />
          </main>
        </ReactQueryProviders>
      </body>
    </html>
  );
}
